import { useEffect, useState, type FormEvent } from "react";
import {
  cleanupDatabase,
  createResetLink,
  createUser,
  deleteUser,
  listAuthEvents,
  listUsers,
  type AuthEvent,
  type UserRow,
} from "./authApi";

const EVENT_LABELS: Record<string, string> = {
  invite_created: "Invite created",
  reset_created: "Reset link created",
  activated: "Password set",
  password_changed: "Password changed",
  account_locked: "Account locked",
};

function eventLabel(e: AuthEvent): string {
  const base = EVENT_LABELS[e.event] ?? e.event;
  return e.event === "activated" && e.detail ? `${base} (${e.detail})` : base;
}

// Admin-only user management. Kept deliberately simple: list, add, remove.
export function UsersModal({
  currentUserId,
  onClose,
}: {
  currentUserId: number;
  onClose: () => void;
}) {
  const [users, setUsers] = useState<UserRow[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [email, setEmail] = useState("");
  const [displayName, setDisplayName] = useState("");
  const [role, setRole] = useState<"member" | "admin">("member");
  const [busy, setBusy] = useState(false);
  const [cleaning, setCleaning] = useState(false);
  const [cleanupMsg, setCleanupMsg] = useState<string | null>(null);
  // The one-time link generated by the most recent "Add user" (invite) or
  // "Reset" (reset), shown once for the admin to copy and hand to the user.
  const [invite, setInvite] = useState<
    { kind: "invite" | "reset"; email: string; link: string; hours: number } | null
  >(null);
  const [copied, setCopied] = useState(false);
  const [events, setEvents] = useState<AuthEvent[] | null>(null);
  const [loadingEvents, setLoadingEvents] = useState(false);

  const refresh = async () => {
    try {
      setUsers(await listUsers());
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };
  useEffect(() => {
    void refresh();
  }, []);

  const add = async (e: FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    setInvite(null);
    setCopied(false);
    try {
      const created = await createUser({ email: email.trim(), displayName: displayName.trim(), role });
      setInvite({
        kind: "invite",
        email: created.user.email,
        link: `${window.location.origin}/activate#${created.inviteToken}`,
        hours: created.expiresHours,
      });
      setEmail("");
      setDisplayName("");
      setRole("member");
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  };

  const copyInvite = async () => {
    if (!invite) return;
    try {
      await navigator.clipboard.writeText(invite.link);
      setCopied(true);
    } catch {
      setCopied(false);
    }
  };

  const remove = async (u: UserRow) => {
    if (!confirm(`Remove ${u.email}? Their projects will be permanently deleted.`)) return;
    setError(null);
    try {
      await deleteUser(u.id);
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    }
  };

  const reset = async (u: UserRow) => {
    setError(null);
    setInvite(null);
    setCopied(false);
    try {
      const r = await createResetLink(u.id);
      setInvite({
        kind: "reset",
        email: r.email,
        link: `${window.location.origin}/activate#${r.token}`,
        hours: r.expiresHours,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    }
  };

  const toggleLog = async () => {
    if (events) {
      setEvents(null);
      return;
    }
    setLoadingEvents(true);
    setError(null);
    try {
      setEvents(await listAuthEvents());
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoadingEvents(false);
    }
  };

  const cleanup = async () => {
    setCleaning(true);
    setError(null);
    setCleanupMsg(null);
    try {
      const r = await cleanupDatabase();
      setCleanupMsg(
        `Removed ${r.orphanProjects} orphaned project(s), ${r.expiredSessions} expired session(s), ${r.spentTokens} spent invite(s). Storage reclaimed.`,
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setCleaning(false);
    }
  };

  return (
    <div style={overlay} onClick={onClose}>
      <div style={panel} onClick={(e) => e.stopPropagation()}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <h2 style={{ margin: 0, fontSize: "1.1rem", color: "var(--text)" }}>Users</h2>
          <button onClick={onClose} style={xButton} aria-label="Close">
            ✕
          </button>
        </div>

        <table style={{ width: "100%", borderCollapse: "collapse", marginTop: "1rem", fontSize: "0.9rem" }}>
          <thead>
            <tr style={{ textAlign: "left", color: "var(--text-muted)" }}>
              <th style={th}>Email</th>
              <th style={th}>Name</th>
              <th style={th}>Role</th>
              <th style={th}></th>
            </tr>
          </thead>
          <tbody>
            {users.map((u) => (
              <tr key={u.id} style={{ borderTop: "1px solid var(--border)" }}>
                <td style={td}>{u.email}</td>
                <td style={td}>{u.displayName}</td>
                <td style={{ ...td, color: "var(--text-muted)" }}>{u.role}</td>
                <td style={{ ...td, textAlign: "right", whiteSpace: "nowrap" }}>
                  <button onClick={() => reset(u)} style={linkAction}>
                    Reset
                  </button>
                  {u.id !== currentUserId && (
                    <button onClick={() => remove(u)} style={{ ...linkDanger, marginLeft: "0.75rem" }}>
                      Remove
                    </button>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <form onSubmit={add} style={{ marginTop: "1.25rem", borderTop: "1px solid var(--border)", paddingTop: "1rem" }}>
          <div style={{ fontWeight: 600, marginBottom: "0.25rem", fontSize: "0.9rem", color: "var(--text)" }}>
            Add user
          </div>
          <p style={{ margin: "0 0 0.6rem", fontSize: "0.8rem", color: "var(--text-muted)" }}>
            Creates the account and generates a one-time invite link — the user sets
            their own password.
          </p>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.5rem" }}>
            <input placeholder="Email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required style={field} />
            <input placeholder="Display name" value={displayName} onChange={(e) => setDisplayName(e.target.value)} required style={field} />
            <select value={role} onChange={(e) => setRole(e.target.value as "member" | "admin")} style={field}>
              <option value="member">Member</option>
              <option value="admin">Admin</option>
            </select>
          </div>
          {error && <p style={{ color: "var(--danger)", fontSize: "0.85rem", margin: "0.75rem 0 0" }}>{error}</p>}
          <button type="submit" disabled={busy} style={addButton}>
            {busy ? "Adding…" : "Add user"}
          </button>
        </form>

        {invite && (
          <div style={inviteBox}>
            <div style={{ fontWeight: 600, fontSize: "0.85rem", color: "var(--text)" }}>
              {invite.kind === "reset" ? "Password reset link" : "Invite link"} for {invite.email}
            </div>
            <p style={{ margin: "0.25rem 0 0.6rem", fontSize: "0.78rem", color: "var(--text-muted)" }}>
              Copy this and send it to the user. It can be used once and expires in{" "}
              {invite.hours} hours.
            </p>
            <div style={{ display: "flex", gap: "0.5rem" }}>
              <input readOnly value={invite.link} onFocus={(e) => e.currentTarget.select()} style={{ ...field, flex: 1 }} />
              <button type="button" onClick={copyInvite} style={cleanupButton}>
                {copied ? "Copied" : "Copy"}
              </button>
            </div>
          </div>
        )}

        <div style={{ marginTop: "1.25rem", borderTop: "1px solid var(--border)", paddingTop: "1rem" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
            <div style={{ fontWeight: 600, fontSize: "0.9rem", color: "var(--text)" }}>Security log</div>
            <button onClick={toggleLog} disabled={loadingEvents} style={cleanupButton}>
              {loadingEvents ? "Loading…" : events ? "Hide" : "Show security log"}
            </button>
          </div>
          {events && (
            <div style={{ marginTop: "0.6rem", maxHeight: 220, overflow: "auto" }}>
              {events.length === 0 ? (
                <p style={{ fontSize: "0.8rem", color: "var(--text-muted)", margin: 0 }}>No events yet.</p>
              ) : (
                <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "0.8rem" }}>
                  <thead>
                    <tr style={{ textAlign: "left", color: "var(--text-muted)" }}>
                      <th style={th}>When</th>
                      <th style={th}>Event</th>
                      <th style={th}>Account</th>
                      <th style={th}>By</th>
                    </tr>
                  </thead>
                  <tbody>
                    {events.map((ev) => (
                      <tr key={ev.id} style={{ borderTop: "1px solid var(--border)" }}>
                        <td style={{ ...td, whiteSpace: "nowrap", color: "var(--text-muted)" }}>{ev.createdAt}</td>
                        <td style={td}>{eventLabel(ev)}</td>
                        <td style={td}>{ev.targetEmail ?? "—"}</td>
                        <td style={{ ...td, color: "var(--text-muted)" }}>{ev.actorEmail ?? "system"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              )}
            </div>
          )}
        </div>

        <div style={{ marginTop: "1.25rem", borderTop: "1px solid var(--border)", paddingTop: "1rem" }}>
          <div style={{ fontWeight: 600, marginBottom: "0.25rem", fontSize: "0.9rem", color: "var(--text)" }}>
            Maintenance
          </div>
          <p style={{ margin: "0 0 0.6rem", fontSize: "0.8rem", color: "var(--text-muted)" }}>
            Purge expired sessions and projects left behind by deleted users, and
            reclaim storage.
          </p>
          <button onClick={cleanup} disabled={cleaning} style={cleanupButton}>
            {cleaning ? "Cleaning…" : "Clean up database"}
          </button>
          {cleanupMsg && (
            <span style={{ marginLeft: "0.75rem", fontSize: "0.82rem", color: "var(--text-muted)" }}>
              {cleanupMsg}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

const overlay: React.CSSProperties = {
  position: "fixed",
  inset: 0,
  background: "rgba(0,0,0,0.45)",
  display: "grid",
  placeItems: "center",
  zIndex: 10000,
};
const panel: React.CSSProperties = {
  width: 560,
  maxWidth: "90vw",
  maxHeight: "85vh",
  overflow: "auto",
  background: "var(--bg-panel)",
  color: "var(--text)",
  border: "1px solid var(--border)",
  borderRadius: 12,
  padding: "1.5rem",
  boxShadow: "var(--shadow)",
};
const th: React.CSSProperties = { padding: "0.35rem 0.5rem", fontWeight: 600 };
const td: React.CSSProperties = { padding: "0.4rem 0.5rem", color: "var(--text)" };
const field: React.CSSProperties = {
  padding: "0.45rem 0.55rem",
  background: "var(--bg)",
  color: "var(--text)",
  border: "1px solid var(--border-strong)",
  borderRadius: 8,
  fontSize: "0.9rem",
  fontFamily: "inherit",
};
const xButton: React.CSSProperties = {
  border: "none",
  background: "none",
  fontSize: "1rem",
  cursor: "pointer",
  color: "var(--text-muted)",
};
const linkDanger: React.CSSProperties = {
  border: "none",
  background: "none",
  color: "var(--danger)",
  cursor: "pointer",
  fontSize: "0.85rem",
};
const linkAction: React.CSSProperties = {
  border: "none",
  background: "none",
  color: "var(--accent)",
  cursor: "pointer",
  fontSize: "0.85rem",
};
const addButton: React.CSSProperties = {
  marginTop: "0.9rem",
  padding: "0.5rem 1rem",
  background: "var(--accent)",
  color: "var(--accent-text)",
  border: "none",
  borderRadius: 8,
  cursor: "pointer",
  fontSize: "0.9rem",
  fontWeight: 600,
};
const inviteBox: React.CSSProperties = {
  marginTop: "1rem",
  padding: "0.85rem",
  background: "var(--bg)",
  border: "1px solid var(--border-strong)",
  borderRadius: 8,
};
const cleanupButton: React.CSSProperties = {
  padding: "0.45rem 0.9rem",
  background: "var(--bg-hover)",
  color: "var(--text)",
  border: "1px solid var(--border-strong)",
  borderRadius: 8,
  cursor: "pointer",
  fontSize: "0.85rem",
};
